[package]
name = "lc3-emu"
version = "0.1.0"
authors = ["by77er <39721110+by77er@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
